# Generated by Django 6.0.4 on 2026-05-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogtask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtable',
            old_name='Description',
            new_name='description',
        ),
    ]
