# Generated by Django 6.0.4 on 2026-04-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_completed', models.CharField(choices=[('done', 'Done'), ('not_yet', 'Not Yet')], default='not_yet', max_length=10)),
            ],
        ),
    ]
