# Generated by Django 6.0.4 on 2026-04-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_number', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('admission_date', models.DateField()),
            ],
        ),
    ]
